[2023-10-18T15:57:50.931+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trending_youtube_dag_v1.fetch_trending_videos manual__2023-10-18T15:57:48.260740+00:00 [queued]>
[2023-10-18T15:57:50.941+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trending_youtube_dag_v1.fetch_trending_videos manual__2023-10-18T15:57:48.260740+00:00 [queued]>
[2023-10-18T15:57:50.942+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 4
[2023-10-18T15:57:50.957+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): fetch_trending_videos> on 2023-10-18 15:57:48.260740+00:00
[2023-10-18T15:57:50.963+0000] {standard_task_runner.py:57} INFO - Started process 1356 to run task
[2023-10-18T15:57:50.970+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trending_youtube_dag_v1', 'fetch_trending_videos', 'manual__2023-10-18T15:57:48.260740+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/trending_youtube_dag.py', '--cfg-path', '/tmp/tmpa0odk3nw']
[2023-10-18T15:57:50.972+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask fetch_trending_videos
[2023-10-18T15:57:51.015+0000] {task_command.py:410} INFO - Running <TaskInstance: trending_youtube_dag_v1.fetch_trending_videos manual__2023-10-18T15:57:48.260740+00:00 [running]> on host 0171efe47d59
[2023-10-18T15:57:51.120+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tmtsmrsl' AIRFLOW_CTX_DAG_ID='trending_youtube_dag_v1' AIRFLOW_CTX_TASK_ID='fetch_trending_videos' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T15:57:48.260740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-18T15:57:48.260740+00:00'
[2023-10-18T15:57:51.126+0000] {__init__.py:48} WARNING - file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
[2023-10-18T15:57:52.281+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-10-18T15:57:52.322+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=trending_youtube_dag_v1, task_id=fetch_trending_videos, execution_date=20231018T155748, start_date=20231018T155750, end_date=20231018T155752
[2023-10-18T15:57:52.410+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-10-18T15:57:52.462+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
