[2023-10-18T15:53:50.978+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trending_youtube_dag_v1.load_to_bigquery manual__2023-10-18T15:53:44.262183+00:00 [queued]>
[2023-10-18T15:53:50.984+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trending_youtube_dag_v1.load_to_bigquery manual__2023-10-18T15:53:44.262183+00:00 [queued]>
[2023-10-18T15:53:50.985+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 4
[2023-10-18T15:53:50.993+0000] {taskinstance.py:1350} INFO - Executing <Task(_PythonDecoratedOperator): load_to_bigquery> on 2023-10-18 15:53:44.262183+00:00
[2023-10-18T15:53:50.999+0000] {standard_task_runner.py:57} INFO - Started process 1287 to run task
[2023-10-18T15:53:51.004+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trending_youtube_dag_v1', 'load_to_bigquery', 'manual__2023-10-18T15:53:44.262183+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/trending_youtube_dag.py', '--cfg-path', '/tmp/tmpvnadrzqn']
[2023-10-18T15:53:51.005+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask load_to_bigquery
[2023-10-18T15:53:51.046+0000] {task_command.py:410} INFO - Running <TaskInstance: trending_youtube_dag_v1.load_to_bigquery manual__2023-10-18T15:53:44.262183+00:00 [running]> on host 0171efe47d59
[2023-10-18T15:53:51.108+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tmtsmrsl' AIRFLOW_CTX_DAG_ID='trending_youtube_dag_v1' AIRFLOW_CTX_TASK_ID='load_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2023-10-18T15:53:44.262183+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-18T15:53:44.262183+00:00'
[2023-10-18T15:53:51.577+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trending_youtube_dag.py", line 157, in load_to_bigquery
    table = client.get_table(table_ref)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 1040, in get_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/airflow-yt-project-402408/datasets/youtube/tables/trending_videos?prettyPrint=false: Not found: Table airflow-yt-project-402408:youtube.trending_videos
[2023-10-18T15:53:51.593+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=trending_youtube_dag_v1, task_id=load_to_bigquery, execution_date=20231018T155344, start_date=20231018T155350, end_date=20231018T155351
[2023-10-18T15:53:51.605+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 14 for task load_to_bigquery (404 GET https://bigquery.googleapis.com/bigquery/v2/projects/airflow-yt-project-402408/datasets/youtube/tables/trending_videos?prettyPrint=false: Not found: Table airflow-yt-project-402408:youtube.trending_videos; 1287)
[2023-10-18T15:53:51.665+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-10-18T15:53:51.681+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
